Feat/types подправка сторов и исправление косяков
CaseLabJS/CaseLab2024-team2 pull request #27
Opened 2024-11-08 10:53 UTC by robot122-dev

2024-11-08 11:02 UTC, NadyaGus requested changes
Нужно изменить скрипт, чтобы новые папки создавались с маленькой буквы

2024-11-11 09:37 UTC, NadyaGus reviewed
в паре местах нерешенный конфликт остался + RootStore снова появился)

2024-11-11 09:37 UTC, NadyaGus commented on src/pages/SignUp/ui/SignUp.tsx
> +>>>>>>> main
Нерешенный конфликт

2024-11-11 09:37 UTC, NadyaGus commented on src/api/req-user-data.ts
> +>>>>>>> main
Нерешенный конфликт

2024-11-11 09:37 UTC, NadyaGus commented on src/app/providers/store/RootStore/RootStore.tsx
RootStore мы уже удалили

2024-11-11 10:17 UTC, NadyaGus approved these changes

2024-11-11 11:42 UTC, Night-watch-frontend approved these changes

2024-11-11 11:48 UTC, NikitaSimakov approved these changes

2024-11-11 11:50 UTC, merged