refactor: :recycle: refine delete user-store
CaseLabJS/CaseLab2024-team2 pull request #29
Opened 2024-11-08 17:22 UTC by Night-watch-frontend

Доработал метод удаления юзера в user-store
Добавил обработку try catch
Проверил контракты в api beckend
Изменил ручку для удаления юзера
(Удалить может только админ)

2024-11-09 08:28 UTC, NadyaGus requested changes

2024-11-09 08:28 UTC, NadyaGus commented on src/entities/User/model/UserStore.ts
Так как мы будем хранить информацию о текущем юзере в authStore, то методы `load()` и `init()` можно удалить, они нам тоже тут не нужны будут.
Еще т.к. пока нету нотификашек, можешь ,пожалуйста, добавить на все методы алерты, если произошла ошибка в CRUD-операциях?

2024-11-09 08:28 UTC, NadyaGus commented on src/entities/User/model/UserStore.ts
и поля `this.user` `this.emeil` тоже не нужны

2024-11-09 13:16 UTC, Night-watch-frontend commented on src/entities/User/model/UserStore.ts
Удалил неиспользуемые методы и поля в user-store
Добавил вывод alert во все методы при возникновении ошибки

2024-11-09 13:27 UTC, NadyaGus approved these changes

2024-11-09 18:51 UTC, NikitaSimakov approved these changes

2024-11-10 10:55 UTC, yankaiova approved these changes

2024-11-10 11:59 UTC, merged