Feature/voting store
CaseLabJS/CaseLab2024-team2 pull request #37
Opened 2024-11-11 21:13 UTC by yankaiova

added voting api and voting store

2024-11-11 21:15 UTC, yankaiova commented
Обратите внимание, что одни типы экспортируются из другой сущности Vote. Надо либо типы перенести, либо могу разделить на два стора (один с добавлением голоса, другой - с созданием голосования и получением голосования по id документа)

2024-11-12 14:47 UTC, robot122-dev commented
Я все сделал в vote, переместил voting --> в vote

2024-11-12 14:55 UTC, Night-watch-frontend requested changes
Обнови мейн ветку и смерджи с этой

2024-11-12 16:35 UTC, Night-watch-frontend approved these changes

2024-11-12 20:28 UTC, NikitaSimakov approved these changes

2024-11-12 20:34 UTC, merged