Feat/UI create user
CaseLabJS/CaseLab2024-team2 pull request #48
Opened 2024-11-16 14:48 UTC by DenisTk22

2024-11-16 15:53 UTC, Night-watch-frontend commented on src/widgets/createUser/ui/index.tsx
компоненты необходимо именовать по имени компонента а не index.tsx

2024-11-16 15:54 UTC, Night-watch-frontend commented on src/widgets/createUser/ui/index.tsx
> +export const CreateUser = (): ReactElement => {
export лучше делать через default так как все остальные компоненты используют именно этот экспорт

2024-11-16 15:56 UTC, Night-watch-frontend commented on src/widgets/createUser/ui/index.tsx
> +      <Formik
Всю логику необходимо перенести в features. К тому же было бы не плохо подключить отправку формы к userStore а не просто выводить сообщение

2024-11-16 15:57 UTC, Night-watch-frontend requested changes
Помимо указанных ошибок : не используется MUI

Кстати зачем нам дублирование ? В page имеется signUp и в нем уже есть регистрация связанная со стором .

2024-11-17 14:56 UTC, DenisTk22 commented on src/widgets/createUser/ui/index.tsx
done

2024-11-17 15:02 UTC, DenisTk22 commented on src/widgets/createUser/ui/index.tsx
> +export const CreateUser = (): ReactElement => {
done

2024-11-17 15:06 UTC, DenisTk22 commented on src/widgets/createUser/ui/index.tsx
> +      <Formik
так задание было создать UI виджита из admin menu

2024-11-19 07:08 UTC, NikitaSimakov approved these changes
Отлично!

2024-11-19 09:50 UTC, Night-watch-frontend approved these changes

2024-11-19 19:33 UTC, merged