feat: :sparkles: added create voting process
CaseLabJS/CaseLab2024-team2 pull request #63
Opened 2024-11-25 17:05 UTC by yankaiova

- добавлена страница создания голосования по документу
- добавлен виджет на страницу
- добавлена функцию в стор для проверки, доступно ли голосование пользователю по email

2024-11-25 20:24 UTC, yankaiova commented on src/widgets/createVotingWidget/ui/CreateVotingWidget.tsx
> +        <TextField
Усложнит, надо будет лишние вычисления и лишние библиотеки подтягивать, ради одного инпута (тем более там дедлайн отправляется в формате разницы типо дедлайн - 2 дня и 2 часа)

2024-11-26 00:47 UTC, Night-watch-frontend approved these changes
ок

2024-11-26 07:58 UTC, NadyaGus requested changes

2024-11-26 07:58 UTC, NadyaGus commented on src/app/providers/router/AppRouter.tsx
> +            path: `${ROUTE_CONSTANTS.USER.path}/:documentID${ROUTE_CONSTANTS.CREATE_VOTING.path}`,
На относительный путь карточки документа тоже есть константа в роутере, используй её, сейчас путь неправильный

2024-11-26 07:58 UTC, NadyaGus commented on src/app/providers/router/config/constants.ts
> +  CREATE_VOTING: { path: '/create-voting', ruTitle: 'Голосование' },
Уточни нейминг. Если создать голосование, то по русски тоже пиши "Создание голосования", потому что просто голосование это может быть другая страница

2024-11-26 12:01 UTC, NadyaGus approved these changes

2024-11-26 12:01 UTC, merged