Header updating
CaseLabJS/CaseLab2024-team2 pull request #76
Opened 2024-11-30 15:00 UTC by DenisTk22

- Удалил notifications
- У админа оставил только кнопку log out вместо меню
- Выделил logout в отдельный компонент

2024-12-02 14:22 UTC, NadyaGus requested changes
Надо поправить стили, чтобы кнопки выглядели одинаково и написать все названия кнопок на русском 
![image](https://github.com/user-attachments/assets/86ade4ac-d8d3-420d-b85f-59035f361f52)

2024-12-02 14:22 UTC, NadyaGus commented on src/shared/components/logout/ui/Logout.tsx
> +      Log out
Наверное надо все таки по-русски написать `Выйти из системы` или просто `Выйти`

2024-12-02 17:26 UTC, DenisTk22 commented on src/shared/components/logout/ui/Logout.tsx
> +      Log out
Я поправил: Выход и иконка выхода теперь такая же серая.
Но Профиль это ссылка, а Выход это кнопка, поэтому они выглядят немного по разному. Я думаю что кнопка Выход должна быть обособленной, при большим количестве ссылок это смотрелось бы лучше.

2024-12-02 20:11 UTC, NadyaGus approved these changes

2024-12-03 06:28 UTC, NikitaSimakov approved these changes

2024-12-03 12:02 UTC, merged