Feature/notification
CaseLabJS/CaseLab2024-team2 pull request #77
Opened 2024-12-01 16:09 UTC by NikitaSimakov

### Добавлены уведомления во все приложение

Как работает этот функционал:

- В методе стора пробрасывается ошибка throw error из catch части
- При использовании асинхронной функции в своем реакт-компоненте нужно обернуть её в trycatch
- Вызвать showToast из хука useToast();

> `// GetUser.tsx`
> 
> `const gettingUser = async (user) => {`
> `try {`
> `await authStore.getUser(user);`
> `showToast('success', 'Успешное получение пользователя');`
> `} catch {`
> `showToast('error', 'Ошибка получения пользователя');`
> `}`
> `}
> `

2024-12-01 21:16 UTC, Night-watch-frontend commented
а у меня вопрос: нам действительно нужно столько try catch ? в axios есть встроенный - 1, с торах используем - 2, теперь еще и в компонентах - 3. 3 для одного запроса как то не много ли ?

2024-12-01 21:17 UTC, Night-watch-frontend commented
извиняюсь нечаянно нажал на закрытие ПР

2024-12-02 05:48 UTC, NikitaSimakov commented
> а у меня вопрос: нам действительно нужно столько try catch ? в axios есть встроенный - 1, с торах используем - 2, теперь еще и в компонентах - 3. 3 для одного запроса как то не много ли ?

Согласен что много try catch, но функция showToast является частью хука useToast, который можно использовать только в реакт-компонентах. Тут два варианта, либо переделывать ToastProvider, создать внешнюю переменную в которую будем записывать нашу функцию, тоже не лучший подход. Либо пробрасывать функцию уведомлений в стор в момент вызова, что тоже громоздко и запутанно. По сути try catch кроме громоздкости кода нам ничем не мешают. У тебя есть мысли как упростить?

2024-12-02 14:33 UTC, NadyaGus requested changes
Никит, при закрытии нотификашки с ошибкой происходит новый запрос и мы попадаем в бесконечный цикл закрытия нотификашки и запросов с ошибкой)
Я скинула тебе видео в личку

2024-12-02 17:21 UTC, NikitaSimakov commented
> Никит, при закрытии нотификашки с ошибкой происходит новый запрос и мы попадаем в бесконечный цикл закрытия нотификашки и запросов с ошибкой) Я скинула тебе видео в личку

Фиксед 🤯

2024-12-02 19:36 UTC, Night-watch-frontend commented
![Снимок экрана 2024-12-02 223321](https://github.com/user-attachments/assets/3af313d2-e4e6-4ea6-90e6-6e98bf31efbb)
я просто авторизовался юзером и отключил WR и пошли бесконечные запросы при этом на странице ничего не происходит, периодически появляется табличка "Ошибка" или 'Не удалось получить документы'

2024-12-02 20:15 UTC, NadyaGus commented
> ![Снимок экрана 2024-12-02 223321](https://private-user-images.githubusercontent.com/103284383/391686645-3af313d2-e4e6-4ea6-90e6-6e98bf31efbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNzA3NzEsIm5iZiI6MTczMzE3MDQ3MSwicGF0aCI6Ii8xMDMyODQzODMvMzkxNjg2NjQ1LTNhZjMxM2QyLWU0ZTYtNGVhNi05MGU2LTZlOThiZjMxZWZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQyMDE0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGYzMDJmYWZiNGRkMGZjNTRjY2JkMTY1OTViMWQ3OTM0MjAyMjc3MjVhODM0MTFmNzk5ZDM2NGFkODQ0ZWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ogwvvSRm4rigZ26-Ylg3j2Mke-gaJc5IIQE7wB6U7B0) я просто авторизовался юзером и отключил WR и пошли бесконечные запросы при этом на странице ничего не происходит, периодически появляется табличка "Ошибка" или 'Не удалось получить документы'

это из-за запросов в useEffect, current уже пофикшен, но мы еще и документа в useEffect получаем

2024-12-02 23:16 UTC, Night-watch-frontend commented
да я в принципе не про загрузки а про 'Ошибка' думаю немного странно увидеть такое юзеру. Текст наверное должен быть какой-то более осознанный.

2024-12-03 06:23 UTC, NikitaSimakov commented
> ![Снимок экрана 2024-12-02 223321](https://private-user-images.githubusercontent.com/103284383/391686645-3af313d2-e4e6-4ea6-90e6-6e98bf31efbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDcxNDcsIm5iZiI6MTczMzIwNjg0NywicGF0aCI6Ii8xMDMyODQzODMvMzkxNjg2NjQ1LTNhZjMxM2QyLWU0ZTYtNGVhNi05MGU2LTZlOThiZjMxZWZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNjIwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTI2MzgwMTZiYzU1Yjc2MzM2OThkODFhNGE0OGM2ODVlOTYxZDFmYjhjNmM3NDNlNjU3NDRkM2MzNDMwYmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JE-2ytCPiSGsGMRErDW7uYcgzv1PR3shmNsHCwmPDIU) я просто авторизовался юзером и отключил WR и пошли бесконечные запросы при этом на странице ничего не происходит, периодически появляется табличка "Ошибка" или 'Не удалось получить документы'

После мерджа с фиксом Нади проблема ушла, из хедера триггерился вызов

2024-12-04 14:12 UTC, NadyaGus approved these changes

2024-12-05 17:22 UTC, archvlad approved these changes

2024-12-09 09:39 UTC, merged